# pipeline to deploy infra
name: Deploy Terraform Infra

on: 
  workflow_dispatch

env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      backendrgname: 'terraform-rg'
      backendstorageacctname: 'ajiaccount'
      backendcontainername: 'githubterraformstatepoc'
      backendstatefilename: 'poc_terraform.tfstate'

jobs:
  Terraform-plan:
    runs-on: ubuntu-latest

    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 'Checkout'
        uses: actions/checkout@v3

      # setup terraform
      - name: 'Setup terraform'
        uses: hashicorp/setup-terraform@v2

      # terraform init and backend setup
      - name: 'Terraform init'
        id: init
        run: |
          terraform init `
          -backend-config=resource_group_name=$backendrgname `
          -backend-config=storage_account_name=$backendstorageacctname `
          -backend-config=container_name=$backendcontainername `
          -backend-config=key=$backendstatefilename `
          -backend-config=access_key=${{ secrets.SA_KEY1 }} `
          -input=false
      
      # terraform validate
      - name: 'Terraform Validate'
        id: validate
        run: |
          terraform validate -no-color
      
      # terraform plan
      - name: 'Terraform plan'
        id: plan
        run: |
          terraform plan 
