# pipeline to deploy infra
name: Deploy Terraform Infra

on: 
  workflow_dispatch

env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_NAME }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  Terraform:
    runs-on: ubuntu-latest

    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 'Checkout'
        uses: actions/checkout@v3

      # setup terraform
      - name: 'Setup terraform'
        uses: hashicorp/setup-terraform@v2

      # Runs a single command using the runners shell
      - name: 'Terraform init'
        id: init
        run: |
          terraform init `
          -backend-config=resource_group_name="tf_rgname" `
          -backend-config=storage_account_name=saname `
          -backend-config=container_name=tfstate `
          -backend-config=key=nameoftheconfigfile ` 
          -backend-config=access_key=${{ secrets.sa_key1 }} `
          -input=false
        
      - name: 'Terraform plan'
        id: plan
        run: |
          terraform plan 
